/**
 * Feishu Sender - Send V3 Signals to Feishu
 * Uses OpenClaw's built-in Feishu integration
 */

// Feishu message template
const SIGNAL_CARD_TEMPLATE = {
  config: {
    wide_screen_mode: true
  },
  header: {
    title: {
      tag: 'plain_text',
      content: '📊 V3 Super Brain Signals'
    },
    template: 'blue'
  },
  elements: [
    {
      tag: 'div',
      text: {
        tag: 'plain_text',
        content: ''
      }
    },
    {
      tag: 'div',
      text: {
        tag: 'plain_text',
        content: ''
      }
    },
    {
      tag: 'div',
      text: {
        tag: 'plain_text',
        content: ''
      }
    }
  ]
};

class FeishuSender {
  constructor() {
    this.chatId = null;
  }

  // Set target chat
  setChat(chatId) {
    this.chatId = chatId;
  }

  // Format signal card
  formatSignalCard(data) {
    const card = JSON.parse(JSON.stringify(SIGNAL_CARD_TEMPLATE));
    
    // Header
    card.header.title.content = data.title;
    
    // Summary element
    card.elements[0].text.content = `🎯 ${data.content.split('\n')[0]}`;
    
    // Time element
    card.elements[1].text.content = `🕐 ${new Date().toLocaleString('zh-CN')}`;
    
    // Fields element - show top 5 signals
    if (data.fields && data.fields.length > 0) {
      let fieldText = '📈 *Top Signals:*\n';
      data.fields.slice(0, 5).forEach((f, i) => {
        const emoji = f.change > 10 ? '🚀' : f.change > 5 ? '🔥' : '📈';
        fieldText += `${i+1}. ${emoji} ${f.code} ${f.name} | ¥${f.price} (${f.change > 0 ? '+' : ''}${f.change}%)\n`;
      });
      card.elements[2].text.content = fieldText;
    } else {
      card.elements[2].text.content = 'No signals this scan';
    }
    
    return card;
  }

  // Send to Feishu via message tool
  async sendSignal(data, chatId = null) {
    const targetChat = chatId || this.chatId;
    
    if (!targetChat) {
      console.log('⚠️ No chat ID specified');
      return { success: false, error: 'No chat ID' };
    }

    const card = this.formatSignalCard(data);
    const cardJson = JSON.stringify(card);
    
    // Build rich text message
    let message = `📊 *V3 Super Brain Signals*\n\n`;
    message += `${data.content}\n\n`;
    
    if (data.fields && data.fields.length > 0) {
      message += `🎯 *Top ${Math.min(5, data.fields.length)} Signals:*\n`;
      data.fields.slice(0, 5).forEach((f, i) => {
        const emoji = f.change > 10 ? '🚀' : f.change > 5 ? '🔥' : '📈';
        message += `${i+1}. ${emoji} ${f.code} ${f.name}\n`;
        message += `   💰 ¥${f.price} (${f.change > 0 ? '+' : ''}${f.change}%)\n`;
        message += `   🎯 ${f.rec}\n\n`;
      });
    }
    
    message += `\n_Generated by V3 Super Brain_`;

    return {
      success: true,
      message: message,
      card: card,
      target: targetChat
    };
  }

  // Send to current user (openchat)
  async sendToMe(data) {
    const result = await this.sendSignal(data, 'openchat');
    return result;
  }

  // Create a new group chat for subscribers
  async createSignalChannel(channelName) {
    // This would create a new chat - but we need proper permissions
    // For now, we'll work with existing chats
    console.log('📝 Would create channel:', channelName);
    return { success: true, name: channelName };
  }
}

// Test if run directly
if (require.main === module) {
  const sender = new FeishuSender();
  
  // Test data
  const testData = {
    title: '📊 V3 Super Brain Signals - 03/13',
    content: '🎯 Found 15 signals | Top 10 shown',
    fields: [
      { code: '601012', name: '隆基绿能', price: 18.94, change: 5.23, rec: '🔥 BUY' },
      { code: '000001', name: '平安银行', price: 12.50, change: 3.15, rec: '📈 WATCH' }
    ]
  };
  
  console.log('📤 Test Signal:');
  console.log(sender.formatSignalCard(testData));
}

module.exports = FeishuSender;
