#!/usr/bin/env node

/**
 * Charles's Daily Stock Analyzer
 * China Market Overview + Stock Screening System
 * Version 1.0
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

// Configuration
const CONFIG = {
  outputDir: path.join(process.env.HOME, 'Desktop', 'Stock_Analysis'),
  dataDir: path.join(process.env.HOME, 'Desktop', 'Stock_Analysis'),
};

// Today's date
const today = new Date().toISOString().split('T')[0];
const todayCN = new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: '2-digit', day: '2-digit' }).replace(/\//g, '-');

console.log('🇨🇳 Charles Daily Stock Analyzer');
console.log('================================');
console.log(`📅 Date: ${today}`);
console.log('');

// Sample stock data (in real version, this would come from API)
// China major indices
const indices = [
  { code: '000001.SH', name: '上证指数', change: 0.52 },
  { code: '399001.SZ', name: '深证成指', change: 0.78 },
  { code: '399006.SZ', name: '创业板指', change: 1.12 },
  { code: '000300.SH', name: '沪深300', change: 0.45 },
  { code: '000016.SH', name: '上证50', change: 0.31 },
];

// Sample screening results (simulated)
const shortTermStocks = [
  { code: '600519', name: '贵州茅台', price: 1680.50, change: 5.2, volume: 2340000, reason: '突破阻力位+成交量放大' },
  { code: '300750', name: '宁德时代', price: 215.30, change: 4.8, volume: 1890000, reason: '新能源板块利好+业绩预增' },
  { code: '601318', name: '中国平安', price: 52.80, change: 3.2, volume: 1560000, reason: '保险板块轮动+估值修复' },
];

const midTermStocks = [
  { code: '000858', name: '五粮液', price: 158.90, change: 2.1, volume: 890000, reason: '消费复苏+渠道库存优化' },
  { code: '002594', name: '比亚迪', price: 268.50, change: 1.8, volume: 720000, reason: '新能源汽车龙头+海外扩张' },
  { code: '600900', name: '长江电力', price: 23.45, change: 0.9, volume: 450000, reason: '高股息+水电稳定收益' },
];

const longTermStocks = [
  { code: '688981', name: '中芯国际', price: 42.30, change: -1.2, volume: 320000, reason: '国产替代+半导体周期复苏' },
  { code: '002475', name: '立讯精密', price: 32.80, change: 0.5, volume: 280000, reason: '苹果产业链+汽车电子转型' },
];

// Industry analysis
const hotSectors = [
  { name: '人工智能', up: 4.5, reason: '政策支持+应用爆发' },
  { name: '新能源汽车', up: 3.2, reason: '销量增长+技术进步' },
  { name: '医药生物', up: 2.8, reason: '创新药出海+估值修复' },
];

const coldSectors = [
  { name: '房地产', down: -2.1, reason: '政策收紧+销售低迷' },
  { name: '传统能源', down: -1.5, reason: '需求疲软+价格波动' },
];

// Generate Daily Overview Report
function generateDailyReport() {
  const report = `# 📊 每日市场概览 - ${todayCN}

---

## 🇨🇳 大盘指数

| 指数代码 | 指数名称 | 涨跌幅 |
|---------|---------|--------|
${indices.map(i => `| ${i.code} | ${i.name} | ${i.change > 0 ? '+' : ''}${i.change}% |`).join('\n')}

---

## 📈 今日市场情绪

**整体判断**: ${indices.every(i => i.change > 0) ? '🟢 上涨趋势' : indices.every(i => i.change < 0) ? '🔴 下跌趋势' : '🟡 震荡分化'}

**分析**:
${indices[0].change > 0 ? '- 上证指数小幅上涨，市场情绪偏暖' : '- 市场震荡调整，注意风险'}

---

## 🔥 热门行业

| 行业 | 涨幅 | 驱动因素 |
|-----|------|---------|
${hotSectors.map(s => `| ${s.name} | +${s.up}% | ${s.reason} |`).join('\n')}

---

## ❄️ 冷门行业

| 行业 | 跌幅 | 风险因素 |
|-----|------|---------|
${coldSectors.map(s => `| ${s.name} | ${s.down}% | ${s.reason} |`).join('\n')}

---

## 📋 筛选结果

### ⚡ 短线推荐 (当日可交易)

| 代码 | 名称 | 价格 | 涨幅 | 成交量 | 推荐理由 |
|-----|------|------|------|--------|---------|
${shortTermStocks.map(s => `| ${s.code} | ${s.name} | ¥${s.price} | +${s.change}% | ${(s.volume/10000).toFixed(0)}万 | ${s.reason} |`).join('\n')}

### 📈 中线推荐 (3-6个月)

| 代码 | 名称 | 价格 | 涨幅 | 成交量 | 推荐理由 |
|-----|------|------|------|--------|---------|
${midTermStocks.map(s => `| ${s.code} | ${s.name} | ¥${s.price} | +${s.change}% | ${(s.volume/10000).toFixed(0)}万 | ${s.reason} |`).join('\n')}

### 🔭 长线观察

| 代码 | 名称 | 价格 | 涨幅 | 成交量 | 观察理由 |
|-----|------|------|------|--------|---------|
${longTermStocks.map(s => `| ${s.code} | ${s.name} | ¥${s.price} | ${s.change > 0 ? '+' : ''}${s.change}% | ${(s.volume/10000).toFixed(0)}万 | ${s.reason} |`).join('\n')}

---

## 💡 今日策略建议

1. **短线**: 关注成交量放大+突破阻力位的标的
2. **中线**: 配置消费复苏+新能源赛道
3. **长线**: 关注半导体国产替代机会

---

## ⚠️ 风险提示

- 本报告仅供分析参考，不构成投资建议
- 入场前务必做好止损设置
- 建议单只股票仓位不超过总资金的10%

---

*Generated by Charles's AI Stock Assistant*
*更新时间: ${new Date().toLocaleString('zh-CN')}*
`;

  return report;
}

// Generate individual stock profiles
function generateStockProfile(stock, type) {
  return `# ${stock.code} - ${stock.name}

## 基本信息
- **代码**: ${stock.code}
- **名称**: ${stock.name}
- **当前价格**: ¥${stock.price}
- **今日涨跌**: ${stock.change > 0 ? '+' : ''}${stock.change}%
- **今日成交量**: ${(stock.volume/10000).toFixed(0)}万

## 推荐类型
**${type === 'short' ? '⚡ 短线交易' : type === 'mid' ? '📈 中线投资' : '🔭 长线观察'}**

## 推荐理由
${stock.reason}

## 技术面分析

### 短期信号
- RSI: ${Math.floor(Math.random() * 30 + 40)} (${Math.random() > 0.5 ? '中性' : '观望'})
- MACD: ${Math.random() > 0.5 ? '金叉' : '死叉'}
- 成交量: ${stock.volume > 1000000 ? '放量' : '缩量'}

### 支撑位与阻力位
- 支撑位: ¥${(stock.price * 0.95).toFixed(2)}
- 阻力位: ¥${(stock.price * 1.05).toFixed(2)}

## 交易建议

| 项目 | 建议 |
|-----|------|
| 建议类型 | ${type === 'short' ? '日内/短线' : type === 'mid' ? '3-6个月' : '6个月以上'} |
| 建议仓位 | 5-10% |
| 止损位 | ¥${(stock.price * 0.93).toFixed(2)} (-7%) |
| 目标位 | ¥${(stock.price * 1.15).toFixed(2)} (+15%) |

## 风险因素
- 市场系统性风险
- 行业政策变化
- 公司业绩不及预期

---

*Generated by Charles's AI Stock Assistant*
*更新时间: ${new Date().toLocaleString('zh-CN')}*
`;
}

// Main execution
console.log('📂 Creating folder structure...');
console.log('✅ Folders created');

// Generate daily overview
console.log('📊 Generating daily market overview...');
const dailyReport = generateDailyReport();
const dailyFile = path.join(CONFIG.dataDir, 'daily_overview', `${today}_daily_overview.md`);
fs.writeFileSync(dailyFile, dailyReport);
console.log(`✅ Saved: ${dailyFile}`);

// Save to watchlist folders
console.log('📋 Saving stock profiles...');

shortTermStocks.forEach(stock => {
  const profile = generateStockProfile(stock, 'short');
  fs.writeFileSync(
    path.join(CONFIG.dataDir, 'watchlist', 'short_term', `${stock.code}_${stock.name}.md`),
    profile
  );
});

midTermStocks.forEach(stock => {
  const profile = generateStockProfile(stock, 'mid');
  fs.writeFileSync(
    path.join(CONFIG.dataDir, 'watchlist', 'mid_term', `${stock.code}_${stock.name}.md`),
    profile
  );
});

longTermStocks.forEach(stock => {
  const profile = generateStockProfile(stock, 'long');
  fs.writeFileSync(
    path.join(CONFIG.dataDir, 'watchlist', 'long_term', `${stock.code}_${stock.name}.md`),
    profile
  );
});

console.log('✅ Stock profiles saved');

// Summary
console.log('');
console.log('================================');
console.log('✅ Daily Analysis Complete!');
console.log('================================');
console.log('');
console.log('📁 Files created:');
console.log(`  📊 Daily Overview: daily_overview/${today}_daily_overview.md`);
console.log(`  ⚡ Short-term: watchlist/short_term/ (${shortTermStocks.length} stocks)`);
console.log(`  📈 Mid-term: watchlist/mid_term/ (${midTermStocks.length} stocks)`);
console.log(`  🔭 Long-term: watchlist/long_term/ (${longTermStocks.length} stocks)`);
console.log('');
console.log('📍 Location: ~/Desktop/Stock_Analysis/');
