#!/usr/bin/env node

/**
 * CHARLES'S SUPER BRAIN - WEEKLY PACKAGE GENERATOR
 * Generates comprehensive weekly package every Monday
 */

const fs = require('fs');

const OUTPUT_DIR = process.env.HOME + '/Desktop/Stock_Analysis/daily_overview';
const TODAY = new Date().toISOString().split('T')[0];

function generateWeeklyPackage() {
  const weekStart = TODAY;
  
  let report = `# 📦 CHARLES'S SUPER BRAIN - WEEKLY INTELLIGENCE PACKAGE\n`;
  report += `## Week: ${weekStart} | Generated: ${TODAY}\n\n`;
  
  report += `# 🧠 WEEKLY EXECUTIVE SUMMARY\n\n`;
  report += `## This Week's Theme: "Rotation & Hidden Gems"\n\n`;
  
  report += `| Day | Market Theme | Key Action |\n`;
  report += `|-----|--------------|------------|\n`;
  report += `| Mon | Rotation Start | Accumulate hidden gems |\n`;
  report += `| Tue | Smart Money In | Build positions |\n`;
  report += `| Wed | Sector Rotation | Tech → Consumption |\n`;
  report += `| Thu | Mid-week Check | Review & Adjust |\n`;
  report += `| Fri | Close & Plan | Take profits, set Monday |\n\n`;
  
  // Add today's scan results
  const scanFile = `${OUTPUT_DIR}/COMPREHENSIVE_SCAN_${TODAY}.txt`;
  if (fs.existsSync(scanFile)) {
    const scanContent = fs.readFileSync(scanFile, 'utf8');
    report += `# 📊 TODAY'S COMPREHENSIVE SCAN\n\n`;
    report += scanContent;
  }
  
  report += `\n\n# 🎯 WEEKLY ACTION PLAN\n\n`;
  report += `## Monday: Setup\n`;
  report += `- [ ] Run comprehensive scan\n`;
  report += `- [ ] Identify top 10 hidden gems\n`;
  report += `- [ ] Set up watchlist\n\n`;
  
  report += `## Tuesday-Wednesday: Build Positions\n`;
  report += `- [ ] Enter positions on pullbacks\n`;
  report += `- [ ] Monitor volume for accumulation\n`;
  report += `- [ ] Add to winning positions\n\n`;
  
  report += `## Thursday: Review\n`;
  report += `- [ ] Check sector rotation\n`;
  report += `- [ ] Adjust stops to breakeven\n`;
  report += `- [ ] Add to best performers\n\n`;
  
  report += `## Friday: Profit Taking\n`;
  report += `- [ ] Take partial profits on +10%\n`;
  report += `- [ ] Tighten stops on winners\n`;
  report += `- [ ] Plan next week\n\n`;
  
  report += `# 📈 SECTOR ROTATION MAP\n\n`;
  report += `| Sector | Score | Trend | Position |\n`;
  report += `|--------|-------|-------|----------|\n`;
  report += `| AI/科技 | 92 | → | Take profits |\n`;
  report += `| 新能源 | 88 | ↑ | Hold |\n`;
  report += `| 医药 | 75 | ↑ | Accumulate |\n`;
  report += `| 消费 | 72 | ↑↑ | Rotate IN |\n`;
  report += `| 化工 | 68 | ↑ | Watch |\n`;
  report += `| 金融 | 52 | ↓ | Avoid |\n`;
  report += `| 地产 | 35 | ↓↓ | AVOID |\n\n`;
  
  report += `# ⚠️ RISK RULES\n\n`;
  report += `- **Stop Loss:** -7% hard\n`;
  report += `- **Max Position:** 20% per stock\n`;
  report += `- **Take Partial:** +10%\n`;
  report += `- **Hold Period:** Until May 2026\n`;
  report += `- **NEVER:** Average losers\n\n`;
  
  report += `*🧠 Generated by Charles's Super Brain*\n`;
  report += `*Think Different. Find Hidden. Predict Future.*\n`;
  
  fs.writeFileSync(`${OUTPUT_DIR}/WEEKLY_PACKAGE_${TODAY}.txt`, report);
  console.log(`✅ Weekly package generated: WEEKLY_PACKAGE_${TODAY}.txt`);
}

generateWeeklyPackage();
