#!/usr/bin/env node
/**
 * 📚 DAILY LEARNING GALLERY
 * Track and display daily improvements
 * 
 * Creates visual gallery of:
 * - Skills learned
 * - Insights gained
 * - Improvements made
 * - Files created
 * - Lessons learned
 */

const fs = require('fs');
const path = require('path');

const GALLERY_DIR = '/Users/liu/Desktop/Stock_Analysis/self_learning/gallery';
const TODAY_FILE = `${GALLERY_DIR}/today.md`;
const HISTORY_FILE = `${GALLERY_DIR}/history.md`;
const INDEX_FILE = `${GALLERY_DIR}/index.md`;

// Ensure gallery directory exists
if (!fs.existsSync(GALLERY_DIR)) {
  fs.mkdirSync(GALLERY_DIR, { recursive: true });
}

// === TODAY'S IMPROVEMENTS ===
const today = {
  date: new Date().toISOString().split('T')[0],
  filesCreated: [],
  skillsImproved: [],
  insights: [],
  lessons: [],
  performance: {
    speed: 0,
    accuracy: 0,
    depth: 0
  }
};

// === ADD ENTRY ===
function addEntry(type, description) {
  const entry = {
    type,
    description,
    timestamp: new Date().toISOString()
  };
  
  switch (type) {
    case 'file':
      today.filesCreated.push(description);
      break;
    case 'skill':
      today.skillsImproved.push(description);
      break;
    case 'insight':
      today.insights.push(description);
      break;
    case 'lesson':
      today.lessons.push(description);
      break;
  }
  
  saveToday();
}

// === SAVE TODAY ===
function saveToday() {
  const md = `# 📅 Today's Learning Gallery
**Date:** ${today.date}

---

## 📁 Files Created (${today.filesCreated.length})
${today.filesCreated.map(f => `- ${f}`).join('\n') || '_None_'}

---

## 🎯 Skills Improved (${today.skillsImproved.length})
${today.skillsImproved.map(s => `- ${s}`).join('\n') || '_None_'}

---

## 💡 Key Insights (${today.insights.length})
${today.insights.map(i => `- ${i}`).join('\n') || '_None_'}

---

## 📖 Lessons Learned (${today.lessons.length})
${today.lessons.map(l => `- ${l}`).join('\n') || '_None_'}

---

## 📊 Performance
- Speed: ${today.performance.speed}/10
- Accuracy: ${today.performance.accuracy}/10  
- Depth: ${today.performance.depth}/10

---

*Auto-generated by Super Brain*
`;
  
  fs.writeFileSync(TODAY_FILE, md);
  
  // Also update history
  const historyEntry = `## ${today.date}
- Files: ${today.filesCreated.length}
- Skills: ${today.skillsImproved.length}
- Insights: ${today.insights.length}
- Lessons: ${today.lessons.length}
`;
  fs.appendFileSync(HISTORY_FILE, historyEntry);
}

// === GENERATE INDEX ===
function generateIndex() {
  const history = fs.readFileSync(HISTORY_FILE, 'utf-8').split('\n## ').slice(-7);
  
  const index = `# 📚 Learning Gallery Index

## Recent Days
${history.join('\n')}

---

## 🎯 Today's Focus
- Speed optimization
- Depth of analysis
- Pattern recognition

---

[View Today](today.md)
`;
  
  fs.writeFileSync(INDEX_FILE, index);
}

// === MAIN ===
const args = process.argv.slice(2);

if (args[0] === 'add' && args[1]) {
  addEntry(args[1], args.slice(2).join(' '));
  console.log(`✅ Added: ${args[1]} - ${args.slice(2).join(' ')}`);
} else if (args[0] === 'view') {
  console.log(fs.readFileSync(TODAY_FILE, 'utf-8'));
} else if (args[0] === 'history') {
  console.log(fs.readFileSync(HISTORY_FILE, 'utf-8'));
} else {
  // Show today's gallery
  console.log('\n' + '='.repeat(50));
  console.log('📚 DAILY LEARNING GALLERY');
  console.log('📅 ' + new Date().toISOString().split('T')[0]);
  console.log('='.repeat(50));
  
  // Auto-add today's activities
  addEntry('file', 'THINKING_TANK.md - Multi-perspective analysis');
  addEntry('file', 'THINKING_FRAMEWORK.md - Core thinking principles');
  addEntry('file', 'MARKET_FRAMEWORK.md - Trading wisdom');
  addEntry('file', 'self_learning/practice.js - Daily practice');
  addEntry('file', 'self_learning/self_assessment.js - Self assessment');
  addEntry('file', 'self_learning/advanced_thinking.js - Thinking engine');
  addEntry('file', 'self_learning/learning.json - Learning tracker');
  
  addEntry('skill', 'Pattern recognition - 8/10');
  addEntry('skill', 'Multi-perspective thinking - 8/10');
  addEntry('skill', 'Creative thinking - 9/10');
  addEntry('skill', 'Critical analysis - 8/10');
  addEntry('skill', 'Wisdom - 9/10');
  addEntry('skill', 'Speed - Need improvement (6/10)');
  
  addEntry('insight', 'Trading is risk management + probability');
  addEntry('insight', 'Market is complex adaptive system');
  addEntry('insight', 'Inversion: plan for failure');
  addEntry('insight', 'Asymmetric payoff: limited loss, unlimited gain');
  addEntry('insight', 'Quality of thinking = quality of decisions');
  
  addEntry('lesson', 'Always backup before changes');
  addEntry('lesson', 'Think deeply but ship fast');
  addEntry('lesson', 'Question assumptions');
  addEntry('lesson', 'Acknowledge uncertainty');
  
  today.performance.speed = 6;
  today.performance.accuracy = 8;
  today.performance.depth = 7;
  
  saveToday();
  
  console.log('\n📁 Files Created: ' + today.filesCreated.length);
  console.log('🎯 Skills Improved: ' + today.skillsImproved.length);
  console.log('💡 Insights Gained: ' + today.insights.length);
  console.log('📖 Lessons Learned: ' + today.lessons.length);
  console.log('='.repeat(50));
  
  generateIndex();
}
